import { IChannelsCustomColors } from '../components/Channel/types';
export declare const colors: {
    white: string;
    black1: string;
    blue1: string;
    blue2: string;
    blue3: string;
    blue4: string;
    blue5: string;
    blue6: string;
    blue7: string;
    blue8: string;
    blue9: string;
    blue10: string;
    gray0: string;
    gray1: string;
    gray2: string;
    gray3: string;
    gray4: string;
    gray5: string;
    gray6: string;
    gray7: string;
    gray8: string;
    gray9: string;
    pink1: string;
    purple1: string;
    cobalt1: string;
    primary: string;
    red1: string;
    red2: string;
    red3: string;
    yellow1: string;
    purple: string;
    defaultAvatarBackground: string;
    deleteUserIconBackground: string;
};
export declare const size: {
    mobileS: string;
    mobileM: string;
    mobileL: string;
    tablet: string;
    laptop: string;
    laptopL: string;
    max: string;
};
export declare const device: {
    mobileS: string;
    mobileM: string;
    mobileL: string;
    tablet: string;
    laptop: string;
    laptopL: string;
    max: string;
};
export declare const customColors: IChannelsCustomColors;
export declare const setCustomColors: (colorsKeyValues: IChannelsCustomColors) => void;
