export declare const channelsSelector: (store: any) => any;
export declare const channelsForForwardSelector: (store: any) => any;
export declare const deletedChannelSelector: (store: any) => any;
export declare const addedChannelSelector: (store: any) => any;
export declare const addedToChannelSelector: (store: any) => any;
export declare const hiddenChannelSelector: (store: any) => any;
export declare const visibleChannelSelector: (store: any) => any;
export declare const activeChannelSelector: (store: any) => any;
export declare const channelsLoadingState: (store: any) => any;
export declare const channelsHasNextSelector: (store: any) => any;
export declare const channelsForForwardHasNextSelector: (store: any) => any;
export declare const searchValueSelector: (store: any) => any;
export declare const channelInfoIsOpenSelector: (store: any) => any;
export declare const channelEditModeSelector: (store: any) => any;
export declare const typingIndicatorSelector: (channelId: string) => (store: any) => any;
export declare const channelListWidthSelector: (store: any) => any;
export declare const isDraggingSelector: (store: any) => any;
export declare const draggedAttachmentsSelector: (store: any) => any;
