export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS'
export const SET_CONTACT_LOADING_STATE = 'SET_CONTACT_LOADING_STATE'
export const GET_CONTACTS = 'GET_CONTACTS'
export const SET_CONTACTS = 'SET_CONTACTS'
export const GET_USERS = 'GET_USERS'
export const LOAD_MORE_USERS = 'LOAD_MORE_USERS'
export const SET_USERS_LOADING_STATE = 'SET_USERS_LOADING_STATE'
export const SET_USERS = 'SET_USERS'
export const ADD_USERS = 'ADD_USERS'
export const GET_ROLES = 'GET_ROLES'
export const SET_ROLES = 'SET_ROLES'
export const BLOCK_USERS = 'BLOCK_USERS'
export const UNBLOCK_USERS = 'UNBLOCK_USERS'
export const SET_USER = 'SET_USER'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE'

export const CONNECTION_EVENT_TYPES = {
  TOKEN_WILL_EXPIRE: 'TOKEN_WILL_EXPIRE',
  CONNECTION_STATUS_CHANGED: 'CONNECTION_STATUS_CHANGED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED'
}

export const CONNECTION_STATUS = {
  CONNECTING: 'Connecting',
  CONNECTED: 'Connected',
  CONNECTING_FAILED: 'Failed',
  DISCONNECTED: 'Disconnected'
}
